name: CI
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ["**"]

jobs:
  test:
    name: Run tests and linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.io/library/golang:1.18.3@sha256:a452d6273ad03a47c2f29b898d6bb57630e77baf839651ef77d03e4e049c5bf3
        name: Run unit tests
        with:
          entrypoint: go
          args: test -v ./pkg/...
      - uses: docker://docker.io/library/golang:1.18.3@sha256:a452d6273ad03a47c2f29b898d6bb57630e77baf839651ef77d03e4e049c5bf3
        name: Run go vet
        with:
          entrypoint: go
          args: vet
  build:
    needs: test
    name: Build the binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64, arm64]
        exclude:
          # not yet supported by go
          - GOOS: darwin
            GOARCH: arm64
          - GOOS: windows
            GOARCH: arm64
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.io/library/golang:1.18.3@sha256:a452d6273ad03a47c2f29b898d6bb57630e77baf839651ef77d03e4e049c5bf3
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        with:
          entrypoint: go
          args: build
      - uses: actions/upload-artifact@v2
        with:
          name: imagine-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: imagine

  image:
    needs: test
    name: Build the image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://ghcr.io/errordeveloper/imagine:2ac274f.c3c997d-dev@sha256:bfac14d268f55ab7b32abd936a22c05e830224efd9b46423233c001847124708
        with:
          entrypoint: imagine
          args: build --platform linux/amd64,linux/arm64 --config build.yaml --registry  ghcr.io/errordeveloper  --push
