name: CI
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ["**"]

jobs:
  test:
    name: Run tests and linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://docker.io/library/golang:1.19@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71
        name: Run unit tests
        with:
          entrypoint: go
          args: test -v ./pkg/...
      - uses: docker://docker.io/library/golang:1.19@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71
        name: Run go vet
        with:
          entrypoint: go
          args: vet
  build:
    needs: test
    name: Build the binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64, arm64]
        exclude:
          # not yet supported by go
          - GOOS: darwin
            GOARCH: arm64
          - GOOS: windows
            GOARCH: arm64
    steps:
      - uses: actions/checkout@v3
      - uses: docker://docker.io/library/golang:1.19@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        with:
          entrypoint: go
          args: build -buildvcs=false
      - uses: actions/upload-artifact@v3
        with:
          name: imagine-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: imagine

  image:
    needs: test
    name: Build the image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker://ghcr.io/errordeveloper/imagine:2ac274f.211fc0f-dev@sha256:3bbce2620146467f91f148d39c431f6e0682c267772172739f75e9fb7d567e4c
        env:
          ANY_REGISTRY_DISABLE: true
          DOCKER_HUB_PUBLIC_ACCESS_ONLY: true
          GHCR_USERNAME: $GITHUB_ACTOR
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: imagine
          args: build --platform linux/amd64,linux/arm64 --config build.yaml --registry ghcr.io/errordeveloper --push
